"""Add discount_price to Material

Revision ID: 36ba95bfc4b8
Revises: 2ba24a8a5475
Create Date: 2026-04-02 01:03:02.285381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ba95bfc4b8'
down_revision = '2ba24a8a5475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_column('discount_price')

    # ### end Alembic commands ###
