"""Add phone field to User and completion tracking to Order

Revision ID: 7969ac031b6b
Revises: 8c1221dfd7b5
Create Date: 2026-04-04 13:08:09.803508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7969ac031b6b'
down_revision = '8c1221dfd7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('admin_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('approved_at')
        batch_op.drop_column('admin_approved')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('driver_completed')

    # ### end Alembic commands ###
